apiVersion: v1
kind: ConfigMap
metadata:
  name: spendwise-config
  namespace: spendwise
data:
  APP_ENV: "production"
  LOG_LEVEL: "INFO"

  AUTH_SERVICE_PORT: "5001"
  TRANSACTION_SERVICE_PORT: "5002"
  WEB_APP_PORT: "5000"

  AUTH_SERVICE_URL: "http://auth-service:5001"
  TRANSACTION_SERVICE_URL: "http://transaction-service:5002"

  SERVICE_TIMEOUT_SECONDS: "5"
  JWT_EXPIRES_MINUTES: "120"

  SESSION_COOKIE_SECURE: "false"
  SESSION_COOKIE_HTTPONLY: "true"
  SESSION_COOKIE_SAMESITE: "Lax"

  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"