apiVersion: v1
kind: Secret
metadata:
  name: spendwise-secret
  namespace: spendwise
type: Opaque
stringData:
  POSTGRES_USER: "spendwise_user"
  POSTGRES_PASSWORD: "spendwise_password"

  JWT_SECRET: "change-this-local-jwt-secret"
  SECRET_KEY: "change-this-local-secret"

  AUTH_DATABASE_URL: "postgresql://spendwise_user:spendwise_password@postgres:5432/spendwise_auth_db"
  TRANSACTION_DATABASE_URL: "postgresql://spendwise_user:spendwise_password@postgres:5432/spendwise_transaction_db"