apiVersion: v1
kind: Service
metadata:
  name: transaction-service
  namespace: spendwise-test-lab
spec:
  type: ClusterIP
  selector:
    app: transaction-service
  ports:
    - name: http
      port: 5002
      targetPort: 5002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
  namespace: spendwise-test-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-service
  template:
    metadata:
      labels:
        app: transaction-service
    spec:
      containers:
        - name: transaction-service
          image: ghcr.io/hashimzaffar/spendwise-transaction-service:6d5987e8207a48fa22649c34d27c64991c377f21
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 5002
          env:
            - name: TRANSACTION_SERVICE_PORT
              value: "5002"
            - name: TRANSACTION_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: spendwise-secrets
                  key: TRANSACTION_DATABASE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: spendwise-secrets
                  key: JWT_SECRET
          envFrom:
            - configMapRef:
                name: spendwise-config
          readinessProbe:
            httpGet:
              path: /ready
              port: 5002
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5002
            initialDelaySeconds: 30
            periodSeconds: 20
